### ISSUE TITLE
 HSTS Header doesn’t exist for Nextcloud 24 (and 25)

### ISSUE THREAD

**Issue by user67x** [sualko/cloud_hsts#20]
Hello,

I want to migrate to the 24th branch of Nextcloud, but I have this message since several months:
![2022-09-02_18-12-29](https://user-images.githubusercontent.com/13274746/188273794-48fd284a-0205-4485-b706-afd7afa5093c.png)
HSTS Header doesn’t exist for Nextcloud 24.

I have ask my web hosting (Infomaniak) and I have no headers activated.

I have deactivate the module this morning, to test my Nextcloud without the module.

I have two choice now:
— wait since HSTS Header create a new version that support Nextcloud 24, than migrate to it
— desactivate the apps and migrate, and perhaps have a security problem

What shloud I do, please? Do you can do somethings for Nextcloud user that have shared server?

Thanks.

**Comment by Indigo744** [comment]
@sualko sorry to bother you again, but the package 0.10.0 on NextCloud repo is still in "beta" hence the update feature still warn about incompatibility for NC 24 or 25.

Any chance to release a final version?

Thanks a lot!
