### ISSUE TITLE
more information ?

### ISSUE THREAD

**Issue by blackcrack** [sualko/cloud_hsts#4]
Hi,

i have see you nice addon, but it's a bit lack of fully information..

what make it directly , for non technical ?
Move it from a normal http-call to ssl/tls https-adress ?
so if i give http://mywebside.dom/nextcloud
move it to https://mywebside.dom/nextcloud 
if i add this plugin ?

this could maybe good if this info also in the Description ..

best regards
Blacky

**Comment by sualko** [comment]
Please look at the readme and follow those links to get a better understanding what this app is doing.

**Comment by blackcrack** [comment]
@sualko 
Hi Klaus,

then add it also at the market description,
or write the same set also on the marketapp..

i can make it also easy.. i don't need to write here a issue for that.. 
not any it is understand so easy what's does ..

or could you maybe link the Faq into the Description 
in the Info from your App in the Market from Nextcloud
Because there is no real info visible ..

best
Blacky

**Comment by sualko** [comment]
Good idea. It would be awesome If you could create a pull request for that.

**Comment by blackcrack** [comment]
in the Store of nextcloud ?
https://apps.nextcloud.com/apps/hsts

moment, you have wrote something about FAQ ! .. :\
